var keybindings = {
    escape: {
        key: "Escape",
        code: 27,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f1: {
        key: "F1",
        code: 112,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f2: {
        key: "F2",
        code: 113,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f3: {
        key: "F3",
        code: 114,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f4: {
        key: "F4",
        code: 115,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f5: {
        key: "F5",
        code: 116,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f6: {
        key: "F6",
        code: 117,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f7: {
        key: "F7",
        code: 118,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f8: {
        key: "F8",
        code: 119,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f9: {
        key: "F9",
        code: 120,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f10: {
        key: "F10",
        code: 121,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f11: {
        key: "F11",
        code: 122,
        function: {
            down: "toggleShadows",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    f12: {
        key: "F12",
        code: 123,
        function: {
            down: "toggleDebug",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    tab: {
        key: "Tab",
        code: 9,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    capslock: {
        key: "CapsLock",
        code: 20,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    shiftleft: {
        key: "Shift",
        code: 16,
        function: {
            down: "run",
            up: "stopRun",
            params_down: [],
            params_up: [],
            holdrepeat: true,
        },
        enabled: true,
    },
    controlleft: {
        key: "Control",
        code: 17,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    altleft: {
        key: "Alt",
        code: 18,
        function: {
            down: "tipToe",
            up: "stopTipToe",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    metaleft: {
        key: "Meta",
        code: 91,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    space: {
        key: " ",
        code: 32,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    enter: {
        key: "Enter",
        code: 13,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpadenter: {
        key: "Enter",
        code: 13,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    backspace: {
        key: "Backspace",
        code: 8,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpadadd: {
        key: "+",
        code: 107,
        function: {
            down: "zoomIn",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpadsubtract: {
        key: "-",
        code: 109,
        function: {
            down: "zoomOut",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    backquote: {
        key: "`",
        code: 192,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit0: {
        key: "0",
        code: 48,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit1: {
        key: "1",
        code: 49,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit2: {
        key: "2",
        code: 50,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit3: {
        key: "3",
        code: 51,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit4: {
        key: "4",
        code: 52,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit5: {
        key: "5",
        code: 53,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit6: {
        key: "6",
        code: 54,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit7: {
        key: "7",
        code: 55,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit8: {
        key: "8",
        code: 56,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    digit9: {
        key: "9",
        code: 57,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    minus: {
        key: "-",
        code: 189,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    equal: {
        key: "=",
        code: 187,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpaddivide: {
        key: "/",
        code: 111,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpadmultiply: {
        key: "*",
        code: 106,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad1: {
        key: "1",
        code: 97,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad2: {
        key: "2",
        code: 98,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad3: {
        key: "3",
        code: 99,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad4: {
        key: "4",
        code: 100,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad5: {
        key: "5",
        code: 101,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad6: {
        key: "6",
        code: 102,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad7: {
        key: "7",
        code: 103,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad8: {
        key: "8",
        code: 104,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad9: {
        key: "9",
        code: 105,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpad0: {
        key: "0",
        code: 96,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numpaddecimal: {
        key: ".",
        code: 110,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    arrowup: {
        key: "ArrowUp",
        code: 38,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    arrowdown: {
        key: "ArrowDown",
        code: 40,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    arrowleft: {
        key: "ArrowLeft",
        code: 37,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    arrowright: {
        key: "ArrowRight",
        code: 39,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keya: {
        key: "A",
        code: 65,
        function: {
            down: "left",
            up: "notLeft",
            params_down: [],
            params_up: [],
            holdrepeat: true,
        },
        enabled: true,
    },
    keyb: {
        key: "B",
        code: 66,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyc: {
        key: "C",
        code: 67,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyd: {
        key: "D",
        code: 68,
        function: {
            down: "right",
            up: "notRight",
            params_down: [],
            params_up: [],
            holdrepeat: true,
        },
        enabled: true,
    },
    keye: {
        key: "E",
        code: 69,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyf: {
        key: "F",
        code: 70,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyg: {
        key: "G",
        code: 71,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyh: {
        key: "H",
        code: 72,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyi: {
        key: "I",
        code: 73,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyj: {
        key: "J",
        code: 74,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyk: {
        key: "K",
        code: 75,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyl: {
        key: "L",
        code: 76,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keym: {
        key: "M",
        code: 77,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyn: {
        key: "N",
        code: 78,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyo: {
        key: "O",
        code: 79,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyp: {
        key: "P",
        code: 80,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyq: {
        key: "Q",
        code: 81,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyr: {
        key: "R",
        code: 82,
        function: {
            down: "reload",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keys: {
        key: "S",
        code: 83,
        function: {
            down: "down",
            up: "notDown",
            params_down: [],
            params_up: [],
            holdrepeat: true,
        },
        enabled: true,
    },
    keyt: {
        key: "T",
        code: 84,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyu: {
        key: "U",
        code: 85,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyv: {
        key: "V",
        code: 86,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyw: {
        key: "W",
        code: 87,
        function: {
            down: "up",
            up: "notUp",
            params_down: [],
            params_up: [],
            holdrepeat: true,
        },
        enabled: true,
    },
    keyx: {
        key: "X",
        code: 88,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyy: {
        key: "Y",
        code: 89,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    keyz: {
        key: "Z",
        code: 90,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    comma: {
        key: ",",
        code: 188,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    period: {
        key: ".",
        code: 190,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    slash: {
        key: "/",
        code: 191,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    semicolon: {
        key: ";",
        code: 186,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    quote: {
        key: "'",
        code: 222,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    bracketleft: {
        key: "[",
        code: 219,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    bracketright: {
        key: "]",
        code: 221,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    backslash: {
        key: "\\",
        code: 220,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    insert: {
        key: "Insert",
        code: 45,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    delete: {
        key: "Delete",
        code: 46,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    home: {
        key: "Home",
        code: 36,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    end: {
        key: "End",
        code: 35,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    pageup: {
        key: "PageUp",
        code: 33,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    pagedown: {
        key: "PageDown",
        code: 34,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
    numlock: {
        key: "NumLock",
        code: 144,
        function: {
            down: "",
            up: "",
            params_down: [],
            params_up: [],
            holdrepeat: false,
        },
        enabled: true,
    },
};

let press = true;
